name: Build ARM QEMU

on:
  workflow_dispatch:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        base_image: [
#          "balenalib/raspberrypi4-64-ubuntu-python:3.9-jammy-build",
          "balenalib/raspberrypi4-64-ubuntu-python:3.10-jammy-build",
          "balenalib/raspberrypi4-64-ubuntu-python:3.11-jammy-build"
        ]

    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
          key: build_v1_${{ matrix.base_image }}

      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2.5.0
        name: Run commands
        id: runcmd
#       ghcr.io/<github_user>/<github_repo>/run-on-arch-<github_user>-<github_repo>-<workflow_name>-<arch>-<distro>
        with:
          env: |
            GITHUB_WORKFLOW: ${{ matrix.base_image }}
          arch: aarch64
          distro: none
          base_image: ${{ matrix.base_image }}
          githubToken: ${{ github.token }}
          # Create cached/volume directories on host
          setup: |
            mkdir -p ~/.ccache

          # Mount cached directories in the container for faster builds
          dockerRunArgs: |
            --volume "${HOME}/.ccache:/root/.ccache" --volume "${PWD}:/repo"

          # Install ccache and gcc/g++ symlinks in the container
          install: |
            apt-get update -q -y
            apt-get install build-essential ccache -q -y
            /usr/sbin/update-ccache-symlinks
            echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
                     
            export PATH="/usr/lib/ccache:$PATH"
            export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)

          run: |
            pip install -r build-requirements.txt
            pip install -r requirements.txt
            pip wheel . --no-deps --no-build-isolation -v -w wheelhouse 

      - name: Copy wheel
        run: |
          mkdir -p ${{ github.sha }}
          cp wheelhouse/*.whl ${{ github.sha }}/

      - name: Upload an artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          if-no-files-found: error
          name: build_artifact
          path: ${{ github.sha }}

  upload-tarballs:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: [ build ]

    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
          path: ${{ github.sha }}

      - name: Set up a release page
        id: setup_release
        run: |
          GHOLI_VERSION=$(python setup.py --version)
          tag_name="$GHOLI_VERSION"
          release_title="gholi $GHOLI_VERSION"
          echo "gholi $GHOLI_VERSION created at $(date)" > body.md
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
          echo "release_title=${release_title}" >> $GITHUB_OUTPUT

      - name: Upload tarballs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.sha }}/*.whl"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.setup_release.outputs.tag_name }}"
          name: "${{ steps.setup_release.outputs.release_title }}"
          allowUpdates: true
          replacesArtifacts: true